/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PortalDashboardRouteImport } from './routes/_portal.dashboard'
import { Route as PortalInventoryRouteImport } from './routes/_portal.inventory'
import { Route as PortalProfileRouteImport } from './routes/_portal.profile'
import { Route as PortalReportsRouteImport } from './routes/_portal.reports'
import { Route as PortalSettingsRouteImport } from './routes/_portal.settings'
import { Route as PortalChallansIndexRouteImport } from './routes/_portal.challans.index'
import { Route as PortalChallansChallanIdRouteImport } from './routes/_portal.challans.$challanId'
import { Route as PortalChallansNewRouteImport } from './routes/_portal.challans.new'
import { Route as PortalCustomersIndexRouteImport } from './routes/_portal.customers.index'
import { Route as PortalCustomersNewRouteImport } from './routes/_portal.customers.new'
import { Route as PortalProductsIndexRouteImport } from './routes/_portal.products.index'
import { Route as PortalProductsNewRouteImport } from './routes/_portal.products.new'
import { Route as PortalCustomersCustomerIdIndexRouteImport } from './routes/_portal.customers.$customerId.index'
import { Route as PortalCustomersCustomerIdEditRouteImport } from './routes/_portal.customers.$customerId.edit'
import { Route as PortalProductsProductIdIndexRouteImport } from './routes/_portal.products.$productId.index'
import { Route as PortalProductsProductIdEditRouteImport } from './routes/_portal.products.$productId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInventoryRoute = PortalInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReportsRoute = PortalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalChallansIndexRoute = PortalChallansIndexRouteImport.update({
  id: '/challans/',
  path: '/challans/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalChallansChallanIdRoute = PortalChallansChallanIdRouteImport.update({
  id: '/challans/$challanId',
  path: '/challans/$challanId',
  getParentRoute: () => PortalRoute,
} as any)
const PortalChallansNewRoute = PortalChallansNewRouteImport.update({
  id: '/challans/new',
  path: '/challans/new',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCustomersIndexRoute = PortalCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCustomersNewRoute = PortalCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProductsIndexRoute = PortalProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProductsNewRoute = PortalProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCustomersCustomerIdIndexRoute =
  PortalCustomersCustomerIdIndexRouteImport.update({
    id: '/customers/$customerId/',
    path: '/customers/$customerId/',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalCustomersCustomerIdEditRoute =
  PortalCustomersCustomerIdEditRouteImport.update({
    id: '/customers/$customerId/edit',
    path: '/customers/$customerId/edit',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalProductsProductIdIndexRoute =
  PortalProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalProductsProductIdEditRoute =
  PortalProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => PortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof PortalDashboardRoute
  '/inventory': typeof PortalInventoryRoute
  '/profile': typeof PortalProfileRoute
  '/reports': typeof PortalReportsRoute
  '/settings': typeof PortalSettingsRoute
  '/challans/$challanId': typeof PortalChallansChallanIdRoute
  '/challans/new': typeof PortalChallansNewRoute
  '/customers/new': typeof PortalCustomersNewRoute
  '/products/new': typeof PortalProductsNewRoute
  '/challans/': typeof PortalChallansIndexRoute
  '/customers/': typeof PortalCustomersIndexRoute
  '/products/': typeof PortalProductsIndexRoute
  '/customers/$customerId/edit': typeof PortalCustomersCustomerIdEditRoute
  '/products/$productId/edit': typeof PortalProductsProductIdEditRoute
  '/customers/$customerId/': typeof PortalCustomersCustomerIdIndexRoute
  '/products/$productId/': typeof PortalProductsProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof PortalDashboardRoute
  '/inventory': typeof PortalInventoryRoute
  '/profile': typeof PortalProfileRoute
  '/reports': typeof PortalReportsRoute
  '/settings': typeof PortalSettingsRoute
  '/challans/$challanId': typeof PortalChallansChallanIdRoute
  '/challans/new': typeof PortalChallansNewRoute
  '/customers/new': typeof PortalCustomersNewRoute
  '/products/new': typeof PortalProductsNewRoute
  '/challans': typeof PortalChallansIndexRoute
  '/customers': typeof PortalCustomersIndexRoute
  '/products': typeof PortalProductsIndexRoute
  '/customers/$customerId/edit': typeof PortalCustomersCustomerIdEditRoute
  '/products/$productId/edit': typeof PortalProductsProductIdEditRoute
  '/customers/$customerId': typeof PortalCustomersCustomerIdIndexRoute
  '/products/$productId': typeof PortalProductsProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_portal': typeof PortalRouteWithChildren
  '/signup': typeof SignupRoute
  '/_portal/dashboard': typeof PortalDashboardRoute
  '/_portal/inventory': typeof PortalInventoryRoute
  '/_portal/profile': typeof PortalProfileRoute
  '/_portal/reports': typeof PortalReportsRoute
  '/_portal/settings': typeof PortalSettingsRoute
  '/_portal/challans/$challanId': typeof PortalChallansChallanIdRoute
  '/_portal/challans/new': typeof PortalChallansNewRoute
  '/_portal/customers/new': typeof PortalCustomersNewRoute
  '/_portal/products/new': typeof PortalProductsNewRoute
  '/_portal/challans/': typeof PortalChallansIndexRoute
  '/_portal/customers/': typeof PortalCustomersIndexRoute
  '/_portal/products/': typeof PortalProductsIndexRoute
  '/_portal/customers/$customerId/edit': typeof PortalCustomersCustomerIdEditRoute
  '/_portal/products/$productId/edit': typeof PortalProductsProductIdEditRoute
  '/_portal/customers/$customerId/': typeof PortalCustomersCustomerIdIndexRoute
  '/_portal/products/$productId/': typeof PortalProductsProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/dashboard'
    | '/inventory'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/challans/$challanId'
    | '/challans/new'
    | '/customers/new'
    | '/products/new'
    | '/challans/'
    | '/customers/'
    | '/products/'
    | '/customers/$customerId/edit'
    | '/products/$productId/edit'
    | '/customers/$customerId/'
    | '/products/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/dashboard'
    | '/inventory'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/challans/$challanId'
    | '/challans/new'
    | '/customers/new'
    | '/products/new'
    | '/challans'
    | '/customers'
    | '/products'
    | '/customers/$customerId/edit'
    | '/products/$productId/edit'
    | '/customers/$customerId'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/_portal'
    | '/signup'
    | '/_portal/dashboard'
    | '/_portal/inventory'
    | '/_portal/profile'
    | '/_portal/reports'
    | '/_portal/settings'
    | '/_portal/challans/$challanId'
    | '/_portal/challans/new'
    | '/_portal/customers/new'
    | '/_portal/products/new'
    | '/_portal/challans/'
    | '/_portal/customers/'
    | '/_portal/products/'
    | '/_portal/customers/$customerId/edit'
    | '/_portal/products/$productId/edit'
    | '/_portal/customers/$customerId/'
    | '/_portal/products/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/dashboard': {
      id: '/_portal/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/inventory': {
      id: '/_portal/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof PortalInventoryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/profile': {
      id: '/_portal/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/reports': {
      id: '/_portal/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof PortalReportsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/settings': {
      id: '/_portal/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/challans/': {
      id: '/_portal/challans/'
      path: '/challans'
      fullPath: '/challans/'
      preLoaderRoute: typeof PortalChallansIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/challans/$challanId': {
      id: '/_portal/challans/$challanId'
      path: '/challans/$challanId'
      fullPath: '/challans/$challanId'
      preLoaderRoute: typeof PortalChallansChallanIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/challans/new': {
      id: '/_portal/challans/new'
      path: '/challans/new'
      fullPath: '/challans/new'
      preLoaderRoute: typeof PortalChallansNewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/customers/': {
      id: '/_portal/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof PortalCustomersIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/customers/new': {
      id: '/_portal/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof PortalCustomersNewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/products/': {
      id: '/_portal/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof PortalProductsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/products/new': {
      id: '/_portal/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof PortalProductsNewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/customers/$customerId/': {
      id: '/_portal/customers/$customerId/'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId/'
      preLoaderRoute: typeof PortalCustomersCustomerIdIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/customers/$customerId/edit': {
      id: '/_portal/customers/$customerId/edit'
      path: '/customers/$customerId/edit'
      fullPath: '/customers/$customerId/edit'
      preLoaderRoute: typeof PortalCustomersCustomerIdEditRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/products/$productId/': {
      id: '/_portal/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof PortalProductsProductIdIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/products/$productId/edit': {
      id: '/_portal/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof PortalProductsProductIdEditRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalInventoryRoute: typeof PortalInventoryRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalReportsRoute: typeof PortalReportsRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalChallansChallanIdRoute: typeof PortalChallansChallanIdRoute
  PortalChallansNewRoute: typeof PortalChallansNewRoute
  PortalCustomersNewRoute: typeof PortalCustomersNewRoute
  PortalProductsNewRoute: typeof PortalProductsNewRoute
  PortalChallansIndexRoute: typeof PortalChallansIndexRoute
  PortalCustomersIndexRoute: typeof PortalCustomersIndexRoute
  PortalProductsIndexRoute: typeof PortalProductsIndexRoute
  PortalCustomersCustomerIdEditRoute: typeof PortalCustomersCustomerIdEditRoute
  PortalProductsProductIdEditRoute: typeof PortalProductsProductIdEditRoute
  PortalCustomersCustomerIdIndexRoute: typeof PortalCustomersCustomerIdIndexRoute
  PortalProductsProductIdIndexRoute: typeof PortalProductsProductIdIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDashboardRoute: PortalDashboardRoute,
  PortalInventoryRoute: PortalInventoryRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalReportsRoute: PortalReportsRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalChallansChallanIdRoute: PortalChallansChallanIdRoute,
  PortalChallansNewRoute: PortalChallansNewRoute,
  PortalCustomersNewRoute: PortalCustomersNewRoute,
  PortalProductsNewRoute: PortalProductsNewRoute,
  PortalChallansIndexRoute: PortalChallansIndexRoute,
  PortalCustomersIndexRoute: PortalCustomersIndexRoute,
  PortalProductsIndexRoute: PortalProductsIndexRoute,
  PortalCustomersCustomerIdEditRoute: PortalCustomersCustomerIdEditRoute,
  PortalProductsProductIdEditRoute: PortalProductsProductIdEditRoute,
  PortalCustomersCustomerIdIndexRoute: PortalCustomersCustomerIdIndexRoute,
  PortalProductsProductIdIndexRoute: PortalProductsProductIdIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
